using System.Collections;
using System.Reflection;
using System.Text;
using System.Text.Json.Serialization;

namespace SvelteSharp.Models;

/// <summary>Generates strict TypeScript declarations from the JSON model contract.</summary>
public sealed class TypeScriptDeclarationGenerator
{
    private readonly ModelContractOptions _options;
    private readonly NullabilityInfoContext _nullability = new();
    private readonly Dictionary<Type, string> _names = new();
    private readonly HashSet<Type> _discovered = new();
    private readonly List<Type> _definitions = new();

    /// <summary>Creates a generator.</summary>
    public TypeScriptDeclarationGenerator(ModelContractOptions? options = null)
    {
        _options = options ?? ModelContractOptions.Default;
    }

    /// <summary>Generates a declaration for <typeparamref name="T" />.</summary>
    public string Generate<T>(string? exportedName = null)
        => Generate(typeof(T), exportedName);

    /// <summary>Generates a declaration for a CLR type.</summary>
    public string Generate(Type type, string? exportedName = null)
    {
        ArgumentNullException.ThrowIfNull(type);

        _names.Clear();
        _discovered.Clear();
        _definitions.Clear();

        var rootName = ToIdentifier(exportedName ?? GetTypeName(type));
        _names[type] = rootName;
        Discover(type);

        var builder = new StringBuilder();
        builder.AppendLine("// Generated by SvelteSharp. Do not edit.");
        builder.AppendLine($"// JSON contract: {_options.Json.PropertyNamingPolicy?.GetType().Name ?? "default"}");
        builder.AppendLine();

        foreach (var definition in _definitions)
        {
            AppendDefinition(builder, definition);
            builder.AppendLine();
        }

        if (!_definitions.Contains(type) && type != typeof(object))
        {
            builder.Append("export type ").Append(rootName).Append(" = ")
                .Append(GetTypeScriptType(type, NullabilityState.NotNull)).AppendLine(";");
        }

        return builder.ToString();
    }

    /// <summary>Generates the declaration and one HTML-safe JSON snapshot.</summary>
    public ModelContract CreateContract(Type type, object? model)
    {
        ArgumentNullException.ThrowIfNull(type);
        var declaration = Generate(type);
        var json = new System.Text.Json.JsonSerializerOptions(_options.Json);
        if (_options.EnumsAsStrings && !json.Converters.Any(converter => converter is JsonStringEnumConverter))
        {
            json.Converters.Add(new JsonStringEnumConverter());
        }

        var snapshot = ModelSnapshotSerializer.Serialize(model, type, json);
        return new ModelContract(type, _names[type], declaration, snapshot);
    }

    private void Discover(Type type)
    {
        type = UnwrapNullable(type);
        if (IsScalar(type) || type == typeof(object))
        {
            return;
        }

        if (TryGetDictionaryValue(type, out var dictionaryValue))
        {
            Discover(dictionaryValue);
            return;
        }

        if (TryGetEnumerableElement(type, out var element))
        {
            Discover(element);
            return;
        }

        if (!IsObjectType(type) || !_discovered.Add(type))
        {
            return;
        }

        if (!_names.ContainsKey(type))
        {
            _names[type] = ToIdentifier(GetTypeName(type));
        }

        _definitions.Add(type);
        foreach (var property in GetSerializableProperties(type))
        {
            var propertyType = property.PropertyType;
            Discover(UnwrapNullable(propertyType));
        }
    }

    private void AppendDefinition(StringBuilder builder, Type type)
    {
        var name = _names[type];
        builder.Append("export interface ").Append(name).AppendLine(" {");

        foreach (var property in GetSerializableProperties(type))
        {
            var jsonName = GetJsonName(property);
            var propertyName = IsValidIdentifier(jsonName) ? jsonName : $"\"{jsonName}\"";
            var nullable = GetNullability(property) == NullabilityState.Nullable;
            var optional = property.GetCustomAttribute<JsonIgnoreAttribute>()?.Condition
                is JsonIgnoreCondition.WhenWritingNull or JsonIgnoreCondition.WhenWritingDefault;
            builder.Append("  ").Append(propertyName).Append(optional ? "?" : string.Empty).Append(": ")
                .Append(GetTypeScriptType(property.PropertyType, nullable ? NullabilityState.Nullable : NullabilityState.NotNull))
                .AppendLine(";");
        }

        builder.AppendLine("}");
    }

    private string GetTypeScriptType(Type type, NullabilityState nullability)
    {
        var nullable = nullability == NullabilityState.Nullable;
        var unwrapped = UnwrapNullable(type);
        string result;

        if (unwrapped == typeof(string) || unwrapped == typeof(char) || unwrapped == typeof(Guid)
            || unwrapped == typeof(Uri) || unwrapped == typeof(DateTime) || unwrapped == typeof(DateTimeOffset)
            || unwrapped == typeof(DateOnly) || unwrapped == typeof(TimeOnly) || unwrapped == typeof(TimeSpan))
        {
            result = "string";
        }
        else if (unwrapped == typeof(bool))
        {
            result = "boolean";
        }
        else if (unwrapped.IsEnum)
        {
            result = UsesStringEnums
                ? string.Join(" | ", Enum.GetNames(unwrapped).Select(name => $"\"{name}\""))
                : "number";
        }
        else if (IsNumber(unwrapped))
        {
            result = "number";
        }
        else if (TryGetDictionaryValue(unwrapped, out var dictionaryValue))
        {
            result = $"Record<string, {GetTypeScriptType(dictionaryValue, NullabilityState.Unknown)}>";
        }
        else if (TryGetEnumerableElement(unwrapped, out var element))
        {
            result = $"Array<{GetTypeScriptType(element, NullabilityState.Unknown)}>";
        }
        else if (unwrapped == typeof(object))
        {
            result = "unknown";
        }
        else if (IsObjectType(unwrapped))
        {
            if (!_names.TryGetValue(unwrapped, out var name))
            {
                name = ToIdentifier(GetTypeName(unwrapped));
                _names[unwrapped] = name;
            }

            result = name;
        }
        else
        {
            throw new ModelContractException($"The model type '{type}' is not supported by the JSON contract.");
        }

        return nullable ? $"{result} | null" : result;
    }

    private static IEnumerable<PropertyInfo> GetSerializableProperties(Type type)
        => type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(property => property.GetMethod is not null && property.GetMethod.IsPublic)
            .Where(property => property.GetIndexParameters().Length == 0)
            .Where(property => property.GetCustomAttribute<JsonIgnoreAttribute>()?.Condition != JsonIgnoreCondition.Always)
            .OrderBy(property => property.GetCustomAttribute<JsonPropertyOrderAttribute>()?.Order ?? 0)
            .ThenBy(property => property.MetadataToken);

    private string GetJsonName(PropertyInfo property)
        => property.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name
            ?? _options.Json.PropertyNamingPolicy?.ConvertName(property.Name)
            ?? property.Name;

    private NullabilityState GetNullability(PropertyInfo property)
        => _nullability.Create(property).ReadState;

    private static bool IsScalar(Type type)
        => type.IsPrimitive || type.IsEnum || type == typeof(decimal) || type == typeof(string)
            || type == typeof(Guid) || type == typeof(Uri) || type == typeof(DateTime)
            || type == typeof(DateTimeOffset) || type == typeof(DateOnly) || type == typeof(TimeOnly)
            || type == typeof(TimeSpan);

    private static bool IsNumber(Type type)
        => type == typeof(byte) || type == typeof(sbyte) || type == typeof(short) || type == typeof(ushort)
            || type == typeof(int) || type == typeof(uint) || type == typeof(long) || type == typeof(ulong)
            || type == typeof(float) || type == typeof(double) || type == typeof(decimal);

    private static bool IsObjectType(Type type)
        => type.IsClass && type != typeof(string) && !typeof(Delegate).IsAssignableFrom(type)
            && !typeof(Stream).IsAssignableFrom(type);

    private static bool TryGetEnumerableElement(Type type, out Type element)
    {
        if (type.IsArray)
        {
            element = type.GetElementType()!;
            return true;
        }

        var enumerable = type.GetInterfaces()
            .Append(type)
            .FirstOrDefault(candidate => candidate.IsGenericType
                && candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>));
        element = enumerable?.GetGenericArguments()[0]!;
        return enumerable is not null;
    }

    private static bool TryGetDictionaryValue(Type type, out Type value)
    {
        var dictionary = type.GetInterfaces()
            .Append(type)
            .FirstOrDefault(candidate => candidate.IsGenericType
                && (candidate.GetGenericTypeDefinition() == typeof(IDictionary<,>)
                    || candidate.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>)));

        if (dictionary is null)
        {
            value = null!;
            return false;
        }

        var key = dictionary.GetGenericArguments()[0];
        if (key != typeof(string))
        {
            throw new ModelContractException($"Dictionary keys must be strings; '{key}' is not supported.");
        }

        value = dictionary.GetGenericArguments()[1];
        return true;
    }

    private static Type UnwrapNullable(Type type)
        => Nullable.GetUnderlyingType(type) ?? type;

    private static string GetTypeName(Type type)
        => type.GetCustomAttribute<SvelteModelAttribute>()?.Name
            ?? type.Name.Split('`')[0];

    private static string ToIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        if (builder.Length == 0 || char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    private static bool IsValidIdentifier(string value)
        => value.Length > 0 && (char.IsLetter(value[0]) || value[0] == '_')
            && value.Skip(1).All(character => char.IsLetterOrDigit(character) || character == '_');

    private bool UsesStringEnums
        => _options.EnumsAsStrings || _options.Json.Converters.Any(converter => converter is JsonStringEnumConverter);
}
