using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using SvelteSharp.Rendering;

namespace SvelteSharp.AspNetCore;

/// <summary>Maps the allowlisted browser assets generated by SvelteSharp.</summary>
public static class EndpointRouteBuilderExtensions
{
    /// <summary>
    /// Maps assets under an immutable build ID URL. Server graphs are never returned by
    /// this endpoint because they are not put in <see cref="SvelteAssetStore" />.
    /// </summary>
    public static IEndpointRouteBuilder MapSvelteSharpAssets(
        this IEndpointRouteBuilder endpoints,
        string pattern = "/_svelte/v{buildId}/{**path}")
    {
        ArgumentNullException.ThrowIfNull(endpoints);
        endpoints.MapGet(pattern, async context =>
        {
            var buildId = context.Request.RouteValues["buildId"]?.ToString();
            var path = context.Request.RouteValues["path"]?.ToString();
            if (string.IsNullOrWhiteSpace(buildId) || string.IsNullOrWhiteSpace(path))
            {
                context.Response.StatusCode = StatusCodes.Status404NotFound;
                return;
            }

            var store = context.RequestServices.GetService<SvelteAssetStore>();
            if (store is null || !store.TryGet(buildId, path, out var asset) || asset is null)
            {
                context.Response.StatusCode = StatusCodes.Status404NotFound;
                return;
            }

            context.Response.ContentType = asset.ContentType;
            context.Response.Headers.CacheControl = "public,max-age=31536000,immutable";
            await context.Response.WriteAsync(asset.Content, context.RequestAborted);
        });
        return endpoints;
    }
}
