using System.Text.Json;
using System.Reflection;
using SvelteSharp.Compiler;
using SvelteSharp.Models;

namespace SvelteSharp.AspNetCore;

/// <summary>Application-wide SvelteSharp configuration.</summary>
public sealed class SvelteSharpOptions
{
    /// <summary>Directory containing logical <c>.svelte</c> views.</summary>
    public string ViewsPath { get; set; } = "Views";

    /// <summary>
    /// Directory populated by the setup step with generated Svelte/compiler runtime files.
    /// It is intentionally not part of the SvelteSharp assembly or package.
    /// </summary>
    public string? SvelteToolchainPath { get; set; }

    /// <summary>
    /// Directory containing versioned build artifacts generated by
    /// <c>SvelteSharp.Build</c>. When present, runtime compilation and native
    /// bundling are skipped and the embedded JavaScript engine consumes these
    /// artifacts directly.
    /// </summary>
    public string? BuildOutputPath { get; set; }

    /// <summary>
    /// Allows request-time compiler and native bundler fallback when build
    /// artifacts are unavailable. Keep this disabled for the single-process
    /// production path.
    /// </summary>
    public bool AllowRuntimeBuildFallback { get; set; }

    /// <summary>Engine selected for compiler execution.</summary>
    public SvelteJavaScriptEngine CompilerEngine { get; set; } = SvelteJavaScriptEngine.Jint;

    /// <summary>Engine selected for production SSR execution.</summary>
    public SvelteJavaScriptEngine SsrEngine { get; set; } = SvelteJavaScriptEngine.Jint;

    /// <summary>Fixed dependency-lock hash included in build IDs.</summary>
    public string DependencyLockHash { get; set; } = "none";

    /// <summary>Compiler configuration.</summary>
    public SvelteCompilerOptions Compiler { get; set; } = new()
    {
        SvelteVersion = "5",
        CompilerVersion = SvelteCompilerBundle.Version
    };

    /// <summary>JSON contract options shared by model declarations and snapshots.</summary>
    public JsonSerializerOptions ModelJson { get; set; } = new(JsonSerializerDefaults.Web)
    {
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.Default
    };

    /// <summary>Whether detailed exception pages can include source diagnostics.</summary>
    public bool IncludeDetailedErrors { get; set; }

    /// <summary>Default response cache policy for generated HTML.</summary>
    public string CacheControl { get; set; } = "no-store";

    /// <summary>Optional CSP nonce factory applied to generated module scripts.</summary>
    public Func<Microsoft.AspNetCore.Http.HttpContext, string?>? CspNonceFactory { get; set; }

    /// <summary>Uses the built-in Node-free compiler baseline.</summary>
    public bool UseManagedCompilerBaseline { get; set; } = true;

    /// <summary>Uses the built-in Node-free SSR baseline.</summary>
    public bool UseManagedSsrBaseline { get; set; } = true;
}

/// <summary>Fluent registration object returned by <see cref="ServiceCollectionExtensions.AddSvelteSharp" />.</summary>
public sealed class SvelteSharpBuilder
{
    internal SvelteSharpBuilder(
        Microsoft.Extensions.DependencyInjection.IServiceCollection services,
        SvelteSharpOptions options,
        SvelteModelRegistry modelRegistry)
    {
        Services = services;
        Options = options;
        ModelRegistry = modelRegistry;
    }

    /// <summary>The service collection being configured.</summary>
    public Microsoft.Extensions.DependencyInjection.IServiceCollection Services { get; }

    /// <summary>The mutable application options.</summary>
    public SvelteSharpOptions Options { get; }

    /// <summary>The explicit model registry used by this builder.</summary>
    public SvelteModelRegistry ModelRegistry { get; }

    /// <summary>Selects Jint for SSR explicitly.</summary>
    public SvelteSharpBuilder UseJintForSsr()
    {
        Options.SsrEngine = SvelteJavaScriptEngine.Jint;
        Options.UseManagedSsrBaseline = false;
        return RegisterAdapter("SvelteSharp.Engine.Jint", "RegisterSsr");
    }

    /// <summary>Selects Okojo for SSR explicitly.</summary>
    public SvelteSharpBuilder UseOkojoForSsr()
    {
        Options.SsrEngine = SvelteJavaScriptEngine.Okojo;
        Options.UseManagedSsrBaseline = false;
        return RegisterAdapter("SvelteSharp.Engine.Okojo", "RegisterSsr");
    }

    /// <summary>Selects Jint for compiler execution.</summary>
    public SvelteSharpBuilder UseJintForCompiler()
    {
        Options.CompilerEngine = SvelteJavaScriptEngine.Jint;
        Options.UseManagedCompilerBaseline = false;
        return RegisterAdapter("SvelteSharp.Engine.Jint", "RegisterCompiler");
    }

    /// <summary>Selects Okojo for compiler execution.</summary>
    public SvelteSharpBuilder UseOkojoForCompiler()
    {
        Options.CompilerEngine = SvelteJavaScriptEngine.Okojo;
        Options.UseManagedCompilerBaseline = false;
        return RegisterAdapter("SvelteSharp.Engine.Okojo", "RegisterCompiler");
    }

    /// <summary>Registers a model for explicit TypeScript declaration generation.</summary>
    public SvelteSharpBuilder AddModel<T>()
    {
        ModelRegistry.Register<T>();
        return this;
    }

    private SvelteSharpBuilder RegisterAdapter(string assemblyName, string methodName)
    {
        Assembly assembly;
        try
        {
            assembly = Assembly.Load(new AssemblyName(assemblyName));
        }
        catch (Exception exception)
        {
            throw new InvalidOperationException(
                $"The SvelteSharp adapter '{assemblyName}' is required for this engine selection. " +
                $"Add its package reference before calling the selector.",
                exception);
        }

        var registrar = assembly.GetTypes()
            .SelectMany(type => type.GetMethods(BindingFlags.Public | BindingFlags.Static))
            .FirstOrDefault(method => string.Equals(method.Name, methodName, StringComparison.Ordinal)
                && method.GetParameters() is [{ ParameterType: var parameterType }]
                && parameterType == typeof(SvelteSharpBuilder));
        if (registrar is null)
        {
            throw new InvalidOperationException(
                $"The SvelteSharp adapter '{assemblyName}' does not expose registration method '{methodName}'.");
        }

        try
        {
            return (SvelteSharpBuilder)(registrar.Invoke(null, [this])
                ?? throw new InvalidOperationException($"Adapter registration '{methodName}' returned null."));
        }
        catch (TargetInvocationException exception) when (exception.InnerException is not null)
        {
            throw exception.InnerException;
        }
    }
}
