<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SvelteSharp.BuildTasks</RootNamespace>
    <AssemblyName>SvelteSharp.Build</AssemblyName>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SvelteSharp\SvelteSharp.csproj" />
    <ProjectReference Include="..\SvelteSharp.Engine.Jint\SvelteSharp.Engine.Jint.csproj" />
    <None Include="buildTransitive\SvelteSharp.Build.targets" Pack="true" PackagePath="buildTransitive\" />
    <None Include="$(OutputPath)*.dll" Pack="true" PackagePath="tools\net10.0\" Visible="false" />
    <None Include="$(OutputPath)SvelteSharp.Build.deps.json;$(OutputPath)SvelteSharp.Build.runtimeconfig.json" Pack="true" PackagePath="tools\net10.0\" Visible="false" />
  </ItemGroup>

</Project>
